////////////////////////////////////////////////////Test uchun joy\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

// var typed = new Typed(".typing", {
//     strings: ["margin: <code class='number'>50px</code>", "margin: 150px", "margin: 250px",],
//     typeSpeed: 100,
//     backSpeed: 60,
//     backDelay: 5000,
//     loop: true
    // fadeOut: true,
    // startDelay: 5000,
    // smartBackspace: true,
    // cursorChar: '_',
// });

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


$(document).ready(function(){
    $(".down-1").hide();
    $(".drop-1").click(function(){
        $(".down-1").slideToggle(1000);
    });
    // $(".down-2").hide();
    // $(".drop-2").click(function(){
    //     $(".down-2").slideToggle(1000);
    // });
    // $(".down-3").hide();
    // $(".drop-3").click(function(){
    //     $(".down-3").slideToggle(1000);
    // });
    // $(".down-4").hide();
    // $(".drop-4").click(function(){
    //     $(".down-4").slideToggle(1000);
    // });
    // $(".down-5").hide();
    // $(".drop-5").click(function(){
    //     $(".down-5").slideToggle(1000);
    // });
    // $(".down-6").hide();
    // $(".drop-6").click(function(){
    //     $(".down-6").slideToggle(1000);
    // });
    // $(".down-7").hide();
    // $(".drop-7").click(function(){
    //     $(".down-7").slideToggle(1000);
    // });
    // $(".down-8").hide();
    // $(".drop-8").click(function(){
    //     $(".down-8").slideToggle(1000);
    // });
    // $(".down-9").hide();
    // $(".drop-9").click(function(){
    //     $(".down-9").slideToggle(1000);
    // });
    // $(".down-10").hide();
    // $(".drop-10").click(function(){
    //     $(".down-10").slideToggle(1000);
    // });
    // $(".down-11").hide();
    // $(".drop-11").click(function(){
    //     $(".down-11").slideToggle(1000);
    // });
    // $(".down-12").hide();
    // $(".drop-12").click(function(){
    //     $(".down-12").slideToggle(1000);
    // });
    // $(".down-13").hide();
    // $(".drop-13").click(function(){
    //     $(".down-13").slideToggle(1000);
    // });
    // $(".down-14").hide();
    // $(".drop-14").click(function(){
    //     $(".down-14").slideToggle(1000);
    // });
    // $(".down-15").hide();
    // $(".drop-15").click(function(){
    //     $(".down-15").slideToggle(1000);
    // });
    // $(".down-16").hide();
    // $(".drop-16").click(function(){
    //     $(".down-16").slideToggle(1000);
    // });
    // $(".down-17").hide();
    // $(".drop-17").click(function(){
    //     $(".down-17").slideToggle(1000);
    // });
    // $(".down-18").hide();
    // $(".drop-18").click(function(){
    //     $(".down-18").slideToggle(1000);
    // });
    // $(".down-19").hide();
    // $(".drop-19").click(function(){
    //     $(".down-19").slideToggle(1000);
    // });
    // $(".down-20").hide();
    // $(".drop-20").click(function(){
    //     $(".down-20").slideToggle(1000);
    // });
    // $(".down-21").hide();
    // $(".drop-21").click(function(){
    //     $(".down-21").slideToggle(1000);
    // });
    // $(".down-22").hide();
    // $(".drop-22").click(function(){
    //     $(".down-22").slideToggle(1000);
    // });
    // $(".down-23").hide();
    // $(".drop-23").click(function(){
    //     $(".down-23").slideToggle(1000);
    // });
    // $(".down-24").hide();
    // $(".drop-24").click(function(){
    //     $(".down-24").slideToggle(1000);
    // });
    // $(".down-25").hide();
    // $(".drop-25").click(function(){
    //     $(".down-25").slideToggle(1000);
    // });
    // $(".down-26").hide();
    // $(".drop-26").click(function(){
    //     $(".down-26").slideToggle(1000);
    // });
    // $(".down-27").hide();
    // $(".drop-27").click(function(){
    //     $(".down-27").slideToggle(1000);
    // });
    // $(".down-28").hide();
    // $(".drop-28").click(function(){
    //     $(".down-28").slideToggle(1000);
    // });
    // $(".down-29").hide();
    // $(".drop-29").click(function(){
    //     $(".down-29").slideToggle(1000);
    // });
    // $(".down-30").hide();
    // $(".drop-30").click(function(){
    //     $(".down-30").slideToggle(1000);
    // });
    // $(".down-31").hide();
    // $(".drop-31").click(function(){
    //     $(".down-31").slideToggle(1000);
    // });
    // $(".down-32").hide();
    // $(".drop-32").click(function(){
    //     $(".down-32").slideToggle(1000);
    // });
    // $(".down-33").hide();
    // $(".drop-33").click(function(){
    //     $(".down-33").slideToggle(1000);
    // });
    // $(".down-34").hide();
    // $(".drop-34").click(function(){
    //     $(".down-34").slideToggle(1000);
    // });
    // $(".down-35").hide();
    // $(".drop-35").click(function(){
    //     $(".down-35").slideToggle(1000);
    // });
    // $(".down-36").hide();
    // $(".drop-36").click(function(){
    //     $(".down-36").slideToggle(1000);
    // });
    // $(".down-37").hide();
    // $(".drop-37").click(function(){
    //     $(".down-37").slideToggle(1000);
    // });
    // $(".down-38").hide();
    // $(".drop-38").click(function(){
    //     $(".down-38").slideToggle(1000);
    // });
    // $(".down-39").hide();
    // $(".drop-39").click(function(){
    //     $(".down-39").slideToggle(1000);
    // });
    // $(".down-40").hide();
    // $(".drop-40").click(function(){
    //     $(".down-40").slideToggle(1000);
    // });
    // $(".down-41").hide();
    // $(".drop-41").click(function(){
    //     $(".down-41").slideToggle(1000);
    // });
    // $(".down-42").hide();
    // $(".drop-42").click(function(){
    //     $(".down-42").slideToggle(1000);
    // });
    // $(".down-43").hide();
    // $(".drop-43").click(function(){
    //     $(".down-43").slideToggle(1000);
    // });
    // $(".down-44").hide();
    // $(".drop-44").click(function(){
    //     $(".down-44").slideToggle(1000);
    // });
    // $(".down-45").hide();
    // $(".drop-45").click(function(){
    //     $(".down-45").slideToggle(1000);
    // });
    // $(".down-46").hide();
    // $(".drop-46").click(function(){
    //     $(".down-46").slideToggle(1000);
    // });
    // $(".down-47").hide();
    // $(".drop-47").click(function(){
    //     $(".down-47").slideToggle(1000);
    // });
    // $(".down-48").hide();
    // $(".drop-48").click(function(){
    //     $(".down-48").slideToggle(1000);
    // });
    // $(".down-49").hide();
    // $(".drop-49").click(function(){
    //     $(".down-49").slideToggle(1000);
    // });
    // $(".down-50").hide();
    // $(".drop-50").click(function(){
    //     $(".down-50").slideToggle(1000);
    // });
    // $(".down-51").hide();
    // $(".drop-51").click(function(){
    //     $(".down-51").slideToggle(1000);
    // });
    // $(".down-52").hide();
    // $(".drop-52").click(function(){
    //     $(".down-52").slideToggle(1000);
    // });
    // $(".down-53").hide();
    // $(".drop-53").click(function(){
    //     $(".down-53").slideToggle(1000);
    // });
    // $(".down-54").hide();
    // $(".drop-54").click(function(){
    //     $(".down-54").slideToggle(1000);
    // });
    // $(".down-55").hide();
    // $(".drop-55").click(function(){
    //     $(".down-55").slideToggle(1000);
    // });
    // $(".down-56").hide();
    // $(".drop-56").click(function(){
    //     $(".down-56").slideToggle(1000);
    // });
    // $(".down-57").hide();
    // $(".drop-57").click(function(){
    //     $(".down-57").slideToggle(1000);
    // });
    // $(".down-58").hide();
    // $(".drop-58").click(function(){
    //     $(".down-58").slideToggle(1000);
    // });
    // $(".down-59").hide();
    // $(".drop-59").click(function(){
    //     $(".down-59").slideToggle(1000);
    // });
    // $(".down-60").hide();
    // $(".drop-60").click(function(){
    //     $(".down-60").slideToggle(1000);
    // });
    // $(".down-61").hide();
    // $(".drop-61").click(function(){
    //     $(".down-61").slideToggle(1000);
    // });
    // $(".down-62").hide();
    // $(".drop-62").click(function(){
    //     $(".down-62").slideToggle(1000);
    // });
    // $(".down-63").hide();
    // $(".drop-63").click(function(){
    //     $(".down-63").slideToggle(1000);
    // });
    // $(".down-64").hide();
    // $(".drop-64").click(function(){
    //     $(".down-64").slideToggle(1000);
    // });
    // $(".down-65").hide();
    // $(".drop-65").click(function(){
    //     $(".down-65").slideToggle(1000);
    // });
    // $(".down-66").hide();
    // $(".drop-66").click(function(){
    //     $(".down-66").slideToggle(1000);
    // });
    // $(".down-67").hide();
    // $(".drop-67").click(function(){
    //     $(".down-67").slideToggle(1000);
    // });
    // $(".down-68").hide();
    // $(".drop-68").click(function(){
    //     $(".down-68").slideToggle(1000);
    // });
    // $(".down-69").hide();
    // $(".drop-69").click(function(){
    //     $(".down-69").slideToggle(1000);
    // });
    // $(".down-70").hide();
    // $(".drop-70").click(function(){
    //     $(".down-70").slideToggle(1000);
    // });
    // $(".down-71").hide();
    // $(".drop-71").click(function(){
    //     $(".down-71").slideToggle(1000);
    // });
    // $(".down-72").hide();
    // $(".drop-72").click(function(){
    //     $(".down-72").slideToggle(1000);
    // });
    // $(".down-73").hide();
    // $(".drop-73").click(function(){
    //     $(".down-73").slideToggle(1000);
    // });
    // $(".down-74").hide();
    // $(".drop-74").click(function(){
    //     $(".down-74").slideToggle(1000);
    // });
    // $(".down-75").hide();
    // $(".drop-75").click(function(){
    //     $(".down-75").slideToggle(1000);
    // });
    // $(".down-76").hide();
    // $(".drop-76").click(function(){
    //     $(".down-76").slideToggle(1000);
    // });
    // $(".down-77").hide();
    // $(".drop-77").click(function(){
    //     $(".down-77").slideToggle(1000);
    // });
    // $(".down-78").hide();
    // $(".drop-78").click(function(){
    //     $(".down-78").slideToggle(1000);
    // });
    // $(".down-79").hide();
    // $(".drop-79").click(function(){
    //     $(".down-79").slideToggle(1000);
    // });
    // $(".down-80").hide();
    // $(".drop-80").click(function(){
    //     $(".down-80").slideToggle(1000);
    // });
    // $(".down-81").hide();
    // $(".drop-81").click(function(){
    //     $(".down-81").slideToggle(1000);
    // });
    // $(".down-82").hide();
    // $(".drop-82").click(function(){
    //     $(".down-82").slideToggle(1000);
    // });
    // $(".down-83").hide();
    // $(".drop-83").click(function(){
    //     $(".down-83").slideToggle(1000);
    // });
    // $(".down-84").hide();
    // $(".drop-84").click(function(){
    //     $(".down-84").slideToggle(1000);
    // });
    // $(".down-85").hide();
    // $(".drop-85").click(function(){
    //     $(".down-85").slideToggle(1000);
    // });
    // $(".down-86").hide();
    // $(".drop-86").click(function(){
    //     $(".down-86").slideToggle(1000);
    // });
    // $(".down-87").hide();
    // $(".drop-87").click(function(){
    //     $(".down-87").slideToggle(1000);
    // });
    // $(".down-88").hide();
    // $(".drop-88").click(function(){
    //     $(".down-88").slideToggle(1000);
    // });
    // $(".down-89").hide();
    // $(".drop-89").click(function(){
    //     $(".down-89").slideToggle(1000);
    // });
    // $(".down-90").hide();
    // $(".drop-90").click(function(){
    //     $(".down-90").slideToggle(1000);
    // });
// ///////////////////////////// Qiymat \\\\\\\\\\\\\\\\\\\\\\\\\\\\\ \\
    $(".downs-1").hide();
    $(".drops-1").click(function(){
        $(".downs-1").slideToggle(1000);
    });
    $(".downs-2").hide();
    $(".drops-2").click(function(){
        $(".downs-2").slideToggle(1000);
    });
});
